force-app/main/default/objects/Pricing_Plan__c/Pricing_Plan__c.object-meta.xml
<CustomObject>
    <description>Subscription pricing plan.</description>
    <label>Pricing Plan</label>
    <nameField>
        <label>Pricing Plans Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pricing_Plan__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pricing_Plan__c/fields/ProductName__c.field-meta.xml
<CustomField>
    <fullName>ProductName__c</fullName>
    <description>The name of the product associated with this pricing plan</description>
    <label>Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pricing_Plan__c/fields/Recurrency_Type__c.field-meta.xml
<CustomField>
    <fullName>Recurrency_Type__c</fullName>
    <label>Recurrency Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Recurrency_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricing_Plan__c/fields/Stripe_Price_ID__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Price_ID__c</fullName>
    <externalId>true</externalId>
    <label>Stripe Price ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pricing_Plan__c/fields/Stripe_Subscription__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stripe Subscription</label>
    <referenceTo>Stripe_Subscription__c</referenceTo>
    <relationshipLabel>Pricing Plans</relationshipLabel>
    <relationshipName>Pricing_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pricing_Tier__c/Pricing_Tier__c.object-meta.xml
<CustomObject>
    <label>Pricing Tier</label>
    <nameField>
        <label>Pricing Tier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Tiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Pricing_Tier__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Pricing_Tier__c/fields/Pricing_Plan__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Plan__c</fullName>
    <label>Pricing Plan</label>
    <referenceTo>Pricing_Plan__c</referenceTo>
    <relationshipLabel>Pricing Tiers</relationshipLabel>
    <relationshipName>Pricing_Tiers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pricing_Tier__c/fields/Tier_Number__c.field-meta.xml
<CustomField>
    <fullName>Tier_Number__c</fullName>
    <label>Tier Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pricing_Tier__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/Stripe_Subscription__c.object-meta.xml
<CustomObject>
    <label>Stripe Subscription</label>
    <nameField>
        <displayFormat>SUB-{000000}</displayFormat>
        <label>Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stripe Subscriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Stripe_Subscription__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <defaultValue>&quot;usd&quot;</defaultValue>
    <label>Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stripe_Subscription__c/fields/Pricing_Plan__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The pricing plan associated with this subscription</description>
    <label>Pricing Plan</label>
    <referenceTo>Pricing_Plan__c</referenceTo>
    <relationshipLabel>Stripe Subscriptions</relationshipLabel>
    <relationshipName>Stripe_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Recurrency_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Daily</fullName>
    </customValue>
    <customValue>
        <fullName>Weekly</fullName>
    </customValue>
    <customValue>
        <fullName>Bi-weekly</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>Quarterly</fullName>
    </customValue>
    <customValue>
        <fullName>Yearly</fullName>
    </customValue>
    <masterLabel>Recurrency Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/tests/PricingPlanTriggerHelperTest.cls
@isTest
public class PricingPlanTriggerHelperTest {
    private static User testUser;
    // Mock class for successful Stripe API callout
    private class StripeAPIPriceSuccessMock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"id": "price_1SL0u0F3hNTtzVuGs8NtCjiW", "object": "price", "active": true}');
            res.setStatusCode(200);
            return res;
        }
    }
    @TestSetup
    static void setupTestData() {
        // Create test user with Stripe API Access permission set
        testUser = TestDataFactory.createUserWithPermissionSets(
            new List<String>{'Stripe_API_Access', 'CustomMetadataAccess','Stripe_Integration_User','PricingPlanAndPricingTier'}
        );
    }
    private static User getTestUser() {
        return [SELECT Id FROM User WHERE Email LIKE 'testuser%@testorg.com' LIMIT 1];
    }
    @IsTest
    static void updateStripePriceIdOnRelatedSubscription_insertAndUpdatePriceId_success(){
        User testUser = getTestUser();
        System.runAs(testUser){
            Test.setMock(HttpCalloutMock.class, new StripeAPIPriceSuccessMock());
            // Create test data
            Stripe_Subscription__c subscription = new Stripe_Subscription__c(
                Product_Plan_Name__c = 'Orange'
            );
            insert subscription;
            Pricing_Plan__c pricePlan = new Pricing_Plan__c(
                Stripe_Subscription__c = subscription.Id,
                Currency__c = 'usd',
                Recurrency_Type__c = 'week',
                Amount__c = 400
            );
            insert pricePlan;
            String requestBody = 'currency=' + EncodingUtil.urlEncode(pricePlan.Currency__c, 'UTF-8') +
                                        '&recurring[interval]=' + EncodingUtil.urlEncode(pricePlan.Recurrency_Type__c.toLowerCase(), 'UTF-8') +
                                        '&unit_amount=' + String.valueOf(pricePlan.Amount__c.longValue()) +
                                        '&product=' + EncodingUtil.urlEncode('prod_THa4qnfsETOFa2', 'UTF-8');
                // Create queueable instance
            StripeCalloutQueueable queueable = new StripeCalloutQueueable(
                pricePlan.Id,
                pricePlan.Currency__c,
                pricePlan.Recurrency_Type__c.toString().replace('ily','y').replace('ly',''),
                pricePlan.Amount__c,
                pricePlan.ProductName__c
            );
            StripeChainedCalloutQueueable secondQueueable = new StripeChainedCalloutQueueable(
                pricePlan.Id,
                requestBody
            );
            Test.startTest();
            System.enqueueJob(queueable);
            System.enqueueJob(secondQueueable);
            Test.stopTest();
            Pricing_Plan__c pricingPlanWithId = [SELECT Stripe_Price_ID__c FROM Pricing_Plan__c WHERE Id =: pricePlan.Id];
            // Verify the result
            System.assertEquals('price_1SL0u0F3hNTtzVuGs8NtCjiW', pricingPlanWithId.Stripe_Price_ID__c, 'Stripe_Price_ID__c is updated');
        }
        
    }

    @IsTest
    static void updateAmountOnRelatedSubscription_insertAndUpdateAmount_success(){
        User testUser = getTestUser();
        System.runAs(testUser){
             // Create test data
            Stripe_Subscription__c subscription = new Stripe_Subscription__c(
                Product_Plan_Name__c = 'Orange'
            );
            insert subscription;
            Pricing_Plan__c pricePlan = new Pricing_Plan__c(
                Stripe_Price_ID__c = 'i98u098u09',
                Stripe_Subscription__c = subscription.Id,
                Currency__c = 'usd',
                Recurrency_Type__c = 'week'
            );
            insert pricePlan;
            pricePlan.Amount__c = 24;
            Test.startTest();
            update pricePlan;
            Test.stopTest();
            // Verify the result
            List<Stripe_Subscription__c> updatedSubscription = [SELECT Amount__c FROM Stripe_Subscription__c WHERE Id =: subscription.Id];
            System.assertEquals(24, updatedSubscription[0].Amount__c, 'Stripe_Price_ID__c is updated on related Stripe_Subscription__c');
        }
        
    }

    @IsTest
    static void createPricingTier_insertPricingPlanWithProperName_success(){
         User testUser = getTestUser();
        System.runAs(testUser){
            // Create test data
            Pricing_Plan__c pricePlan = new Pricing_Plan__c(
                Stripe_Price_ID__c = 'i98u098u09',
                Currency__c = 'usd',
                Recurrency_Type__c = 'week',
                Name = 'Basic_Month'
            );
            Test.startTest();
            insert pricePlan;
            Test.stopTest();
            // Verify the result
            List<Pricing_Tier__c> createdPricingTiers = [SELECT Tier_Number__c, Discount__c, Unit_Price__c FROM Pricing_Tier__c WHERE Pricing_Plan__c =: pricePlan.Id];
            System.assertEquals(1, createdPricingTiers.size(), 'Pricing_Tier__c is created');
            System.assertNotEquals(null, createdPricingTiers[0].Tier_Number__c, 'Tier_Number__c is populated');
            System.assertNotEquals(null, createdPricingTiers[0].Discount__c, 'Discount__c is populated');
            System.assertNotEquals(null, createdPricingTiers[0].Unit_Price__c, 'Unit_Price__c is populated');
        }
        
    }
}