force-app/main/default/objects/Contact/fields/Customer_Email__c.field-meta.xml
<CustomField>
    <fullName>Customer_Email__c</fullName>
    <label>Customer Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <label>Customer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Customer_Phone__c.field-meta.xml
<CustomField>
    <fullName>Customer_Phone__c</fullName>
    <label>Customer Phone</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/tests/ContactTriggerHelperTest.cls
@isTest
public class ContactTriggerHelperTest {
    @IsTest
    static void processContactAfterInsert_insertContactWithLastNameAndFirstName_success(){
        Contact cont = new Contact(
            FirstName = 'Test',
            LastName = 'Testov',
            Email = 'testovtest@gmail.com.au',
            Phone = '423423423423423'
        );
        Test.startTest();
        insert cont;
        Test.stopTest();
        List<Stripe_Customer__c> insertedStripeCustomers = [SELECT Customer_Name__c, Customer_Email__c, Customer_Phone__c FROM Stripe_Customer__c WHERE Contact__c =: cont.Id];
        System.assertEquals(1, insertedStripeCustomers.size(), 'Stripe Customer is inserted');
        System.assertEquals(cont.LastName + ' ' + cont.FirstName, insertedStripeCustomers[0].Customer_Name__c, 'Name is same');
        System.assertEquals(cont.Email, insertedStripeCustomers[0].Customer_Email__c, 'Email is same');
        System.assertEquals(cont.Phone, insertedStripeCustomers[0].Customer_Phone__c, 'Phone is same');
    }
    @IsTest
    static void processContactAfterInsert_insertContactWithOnlyLastName_success(){
        Contact cont = new Contact(
            LastName = 'Testov',
            Email = 'testovtest@gmail.com.au',
            Phone = '423423423423423'
        );
        Test.startTest();
        insert cont;
        Test.stopTest();
        List<Stripe_Customer__c> insertedStripeCustomers = [SELECT Customer_Name__c, Customer_Email__c, Customer_Phone__c FROM Stripe_Customer__c WHERE Contact__c =: cont.Id];
        System.assertEquals(1, insertedStripeCustomers.size(), 'Stripe Customer is inserted');
        System.assertEquals(cont.LastName, insertedStripeCustomers[0].Customer_Name__c, 'Name is same');
        System.assertEquals(cont.Email, insertedStripeCustomers[0].Customer_Email__c, 'Email is same');
        System.assertEquals(cont.Phone, insertedStripeCustomers[0].Customer_Phone__c, 'Phone is same');
    }
}